version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  coreapi:
    image: ghcr.io/trustattic/coreapi:latest
    container_name: coreapi
    pull_policy: always
    ports:
      - "8081:8081"
    environment:
      TOKENCIPHER_KEY: 0123456789abcdef
      DB_SOURCE: "postgres://postgres:postgres@postgres:5432/postgres"
      API_PORT: 8081
      DB_MIGRATIONSDIR: "/var/run/ko/migrations"
    entrypoint: "/ko-app/coreapi run"
    depends_on:
      postgres:
        condition: service_healthy

  ui:
    image: ghcr.io/trustattic/ui:latest
    container_name: ui
    pull_policy: always
    ports:
      - "3069:3069"
    environment:
      NUXT_API_KEY: ""
      NUXT_OAUTH_AUTH0_CLIENT_ID: ""
      NUXT_OAUTH_AUTH0_CLIENT_SECRET: ""
      NUXT_OAUTH_AUTH0_DOMAIN: ""
      NUXT_SESSION_PASSWORD: ""
    depends_on:
      coreapi:
        condition: service_started
